default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10

development:
  <<: *default
  database: irinasavkina_development
  username: root
  host: localhost

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
